; PlatformIO Project Configuration File

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
upload_port = COM3
monitor_port = COM3
build_flags = -Wl,-u,vfprintf -lprintf_flt -lm
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
